"""Bilingual copy for the public Vericant landing page."""

LANDING_COPY = {
    "fr": {
        "meta_description": "Vericant réunit ventes, stock, factures, dépenses et vitrines promotionnelles pour les commerces au Sénégal.",
        "og_title": "Vericant — Pilotez votre commerce en toute confiance",
        "og_description": "Vendez, suivez votre stock et partagez vos promotions depuis un seul outil.",
        "page_title": "Vericant — Gestion de commerce, stock et promotions",
        "home_label": "Vericant, accueil", "nav_label": "Navigation principale",
        "nav_how": "Comment ça marche", "nav_marketing": "Vitrine & promos", "nav_features": "Fonctionnalités",
        "login": "Se connecter", "menu_open": "Ouvrir le menu",
        "hero_eyebrow": "Conçu pour les commerces au Sénégal", "hero_title": "Votre commerce.", "hero_emphasis": "Toujours sous contrôle.",
        "hero_lede": "Chaque vente, chaque produit et chaque chiffre réunis dans un outil simple. Travaillez en équipe, suivez plusieurs boutiques et transformez vos produits en promotions partageables.",
        "request_demo": "Demander une démo", "see_how": "Voir comment ça marche", "benefits_label": "Avantages",
        "trust_install": "Aucun logiciel à installer", "trust_devices": "Téléphone, tablette ou ordinateur", "trust_support": "Assistance locale",
        "hero_demo_label": "Aperçu animé d'une vente enregistrée dans Vericant avec mise à jour du stock et du bénéfice",
        "live": "En direct", "new_sale": "Nouvelle vente", "invoice": "Facture", "rice": "Riz parfumé", "oil": "Huile végétale",
        "sale_saved": "Vente enregistrée", "stock_updated": "Stock mis à jour automatiquement", "stock": "Stock", "item_count_label": "articles", "updated": "mis à jour",
        "daily_profit": "Bénéfice du jour", "sales": "Ventes", "invoices_payments": "Factures & paiements", "realtime_moves": "Mouvements en temps réel",
        "finance": "Finances", "expenses_profit": "Dépenses & bénéfices", "marketing": "Marketing", "showcases_promos": "Vitrines & promotions",
        "day_eyebrow": "Une journée avec Vericant", "day_title_1": "Moins de saisie.", "day_title_2": "Plus de visibilité.",
        "day_intro": "Vericant relie les opérations du quotidien pour que chaque action mette automatiquement vos chiffres à jour.",
        "sell_title": "Vendez sans ralentir la file", "sell_text": "Recherchez un article, ajoutez le client et encaissez. La facture est prête à imprimer ou à partager sur WhatsApp.",
        "sell_bullet_1": "Factures standard et thermiques", "sell_bullet_2": "Paiements partiels et soldes clients", "sell_bullet_3": "Partage PDF depuis le téléphone",
        "search_product": "Rechercher un produit…", "rice_bulk": "Riz 25 kg", "oil_bulk": "Huile 20 L", "sugar": "Sucre", "checkout": "Encaisser",
        "numbers_title": "Le stock et les chiffres suivent", "numbers_text": "Chaque vente alimente le tableau de bord et les mouvements de stock. Vous voyez ce qui se vend, ce qui manque et ce que vous gagnez.",
        "numbers_bullet_1": "Alertes de stock faible", "numbers_bullet_2": "Ventes, dépenses et bénéfice net", "numbers_bullet_3": "Historique par période et par boutique",
        "sales_today": "Ventes aujourd'hui", "low_stock": "Stock faible", "remaining": "restants", "view": "Voir",
        "marketing_eyebrow": "Nouveau · Vitrine & promos", "marketing_title": "Votre stock devient une vitrine partageable.",
        "marketing_text": "Sélectionnez vos meilleurs produits, marquez une promotion et partagez une page professionnelle avec vos clients—sans créer un autre site.",
        "choose": "Choisissez", "your_products": "vos produits", "publish": "Publiez", "an_offer": "une offre", "share": "Partagez", "on_whatsapp": "sur WhatsApp",
        "marketing_demo_label": "Aperçu d'une vitrine promotionnelle avec une bouteille de bissap partagée sur WhatsApp", "my_showcase": "Ma vitrine",
        "weekly_promo": "Promotion de la semaine", "fresh_bissap": "Bissap frais", "bissap_alt": "Bouteille de bissap frais",
        "promo_created": "Image promo créée", "shared_whatsapp": "Partagée sur WhatsApp",
        "features_eyebrow": "Tout au même endroit", "features_title_1": "Assez simple pour aujourd'hui.", "features_title_2": "Assez solide pour grandir.",
        "multi_shop": "Multi-boutiques", "multi_shop_text": "Pilotez plusieurs points de vente avec un seul compte et passez de l'un à l'autre simplement.",
        "teamwork": "Travail en équipe", "teamwork_text": "Créez des accès administrateur ou personnel et gardez chaque utilisateur dans le bon magasin.",
        "pro_invoices": "Factures professionnelles", "pro_invoices_text": "Imprimez sur papier standard, thermique ou partagez un PDF directement depuis votre téléphone.",
        "customer_relations": "Relations clients", "customer_relations_text": "Retrouvez les achats, paiements, soldes et coordonnées d'un client sans chercher dans des cahiers.",
        "shareable_promos": "Promotions partageables", "shareable_promos_text": "Créez une vitrine publique, des images produit et des offres prêtes pour WhatsApp.",
        "financial_view": "Vision financière", "financial_view_text": "Suivez ventes, dépenses, prêts et bénéfice net sur la période qui vous intéresse.",
        "account_eyebrow": "Un compte, plusieurs équipes", "account_title": "Votre activité reste connectée, même quand elle grandit.",
        "account_text": "Ajoutez une boutique, invitez un collaborateur et gardez une vision claire de chaque point de vente.",
        "shop_plateau": "Boutique Plateau", "users": "utilisateurs", "warehouse_medina": "Dépôt Médina", "stock_synced": "Stock synchronisé", "shop_thies": "Boutique Thiès", "online": "En ligne",
        "cta_eyebrow": "Prêt à voir Vericant en action ?", "cta_title": "Une démonstration vaut mieux qu'un long discours.",
        "cta_text": "Expliquez-nous votre commerce. Nous vous montrerons comment Vericant peut s'adapter à votre façon de travailler.",
        "talk_whatsapp": "Parler sur WhatsApp", "call_us": "ou appeler le +221 70 828 32 54",
        "question": "Une question ?", "contact_title": "Parlons de votre commerce.",
        "contact_text": "Laissez-nous un message. Pour une réponse plus rapide, vous pouvez aussi nous écrire directement sur WhatsApp.",
        "full_name": "Nom complet", "email": "Email", "message": "Message", "send": "Envoyer le message", "sending": "Envoi en cours…",
        "sent": "Message envoyé. Nous vous répondrons rapidement.", "send_error": "Le message n'a pas pu être envoyé. Écrivez-nous sur WhatsApp ou réessayez plus tard.",
        "tagline": "Le cerveau tranquille de votre commerce.", "explore": "Explorer", "contact": "Contact", "information": "Informations",
        "legal": "Mentions légales", "privacy": "Confidentialité", "client_login": "Connexion client", "rights": "Tous droits réservés.", "footer_note": "Conçu pour les commerces qui avancent.",
        "close": "Fermer", "publisher": "Éditeur :", "phone": "Téléphone :",
        "legal_text": "Les informations de ce site sont fournies à titre informatif. Les textes juridiques complets feront l'objet d'une validation adaptée aux territoires dans lesquels Vericant opère.",
        "privacy_text_1": "Les informations envoyées par le formulaire servent uniquement à répondre à votre demande. Pour demander l'accès, la correction ou la suppression de vos informations, contactez vericant2023@gmail.com.",
        "privacy_text_2": "La vitrine publique utilise un identifiant technique pour mesurer les visites sans afficher votre identité aux commerçants.",
        "whatsapp_demo_url": "https://wa.me/221708283254?text=Bonjour%20Vericant%2C%20je%20souhaite%20voir%20une%20d%C3%A9monstration.",
    },
    "en": {
        "meta_description": "Vericant brings sales, inventory, invoices, expenses and promotional storefronts together for businesses in Senegal.",
        "og_title": "Vericant — Run your business with confidence", "og_description": "Sell, track inventory and share promotions from one simple platform.",
        "page_title": "Vericant — Sales, inventory and business management", "home_label": "Vericant home", "nav_label": "Main navigation",
        "nav_how": "How it works", "nav_marketing": "Storefront & promotions", "nav_features": "Features", "login": "Sign in", "menu_open": "Open menu",
        "hero_eyebrow": "Built for businesses in Senegal", "hero_title": "Your business.", "hero_emphasis": "Always under control.",
        "hero_lede": "Every sale, every product and every number in one simple tool. Work as a team, manage multiple stores and turn products into shareable promotions.",
        "request_demo": "Request a demo", "see_how": "See how it works", "benefits_label": "Benefits", "trust_install": "Nothing to install", "trust_devices": "Phone, tablet or computer", "trust_support": "Local support",
        "hero_demo_label": "Animated Vericant sale showing automatic inventory and profit updates", "live": "Live", "new_sale": "New sale", "invoice": "Invoice", "rice": "Fragrant rice", "oil": "Vegetable oil",
        "sale_saved": "Sale recorded", "stock_updated": "Inventory updated automatically", "stock": "Inventory", "item_count_label": "items", "updated": "updated", "daily_profit": "Today's profit",
        "sales": "Sales", "invoices_payments": "Invoices & payments", "realtime_moves": "Real-time movements", "finance": "Finance", "expenses_profit": "Expenses & profit", "marketing": "Marketing", "showcases_promos": "Storefronts & promotions",
        "day_eyebrow": "A day with Vericant", "day_title_1": "Less data entry.", "day_title_2": "More visibility.", "day_intro": "Vericant connects daily operations so every action automatically updates your numbers.",
        "sell_title": "Sell without slowing the line", "sell_text": "Find an item, add the customer and take payment. The invoice is ready to print or share on WhatsApp.",
        "sell_bullet_1": "Standard and thermal invoices", "sell_bullet_2": "Partial payments and customer balances", "sell_bullet_3": "Share PDFs from your phone", "search_product": "Search for a product…", "rice_bulk": "Rice 25 kg", "oil_bulk": "Oil 20 L", "sugar": "Sugar", "checkout": "Checkout",
        "numbers_title": "Inventory and numbers stay in sync", "numbers_text": "Every sale updates your dashboard and inventory movements. See what is selling, what is running low and what you are earning.",
        "numbers_bullet_1": "Low-stock alerts", "numbers_bullet_2": "Sales, expenses and net profit", "numbers_bullet_3": "History by period and store", "sales_today": "Sales today", "low_stock": "Low stock", "remaining": "remaining", "view": "View",
        "marketing_eyebrow": "New · Storefront & promotions", "marketing_title": "Turn your inventory into a shareable storefront.", "marketing_text": "Select your best products, add a promotion and share a professional page with customers—without building another website.",
        "choose": "Choose", "your_products": "your products", "publish": "Publish", "an_offer": "an offer", "share": "Share", "on_whatsapp": "on WhatsApp",
        "marketing_demo_label": "Promotional storefront featuring a bottle of bissap shared on WhatsApp", "my_showcase": "My storefront", "weekly_promo": "Promotion of the week", "fresh_bissap": "Fresh bissap", "bissap_alt": "Bottle of fresh bissap", "promo_created": "Promo image created", "shared_whatsapp": "Shared on WhatsApp",
        "features_eyebrow": "Everything in one place", "features_title_1": "Simple enough for today.", "features_title_2": "Powerful enough to grow.",
        "multi_shop": "Multiple stores", "multi_shop_text": "Manage several locations from one account and switch between them easily.", "teamwork": "Teamwork", "teamwork_text": "Create administrator or staff access and keep every user in the right store.",
        "pro_invoices": "Professional invoices", "pro_invoices_text": "Print on standard or thermal paper, or share a PDF directly from your phone.", "customer_relations": "Customer relationships", "customer_relations_text": "Find a customer's purchases, payments, balance and contact details without searching through notebooks.",
        "shareable_promos": "Shareable promotions", "shareable_promos_text": "Create a public storefront, product images and offers ready for WhatsApp.", "financial_view": "Financial overview", "financial_view_text": "Track sales, expenses, loans and net profit for any period.",
        "account_eyebrow": "One account, multiple teams", "account_title": "Your business stays connected as it grows.", "account_text": "Add a store, invite a teammate and keep a clear view of every location.",
        "shop_plateau": "Plateau store", "users": "users", "warehouse_medina": "Medina warehouse", "stock_synced": "Inventory synced", "shop_thies": "Thiès store", "online": "Online",
        "cta_eyebrow": "Ready to see Vericant in action?", "cta_title": "A demonstration is worth a thousand words.", "cta_text": "Tell us about your business. We will show you how Vericant can adapt to the way you work.", "talk_whatsapp": "Chat on WhatsApp", "call_us": "or call +221 70 828 32 54",
        "question": "Have a question?", "contact_title": "Let's talk about your business.", "contact_text": "Leave us a message. For a faster response, you can also contact us directly on WhatsApp.",
        "full_name": "Full name", "email": "Email", "message": "Message", "send": "Send message", "sending": "Sending…", "sent": "Message sent. We will get back to you shortly.", "send_error": "Your message could not be sent. Contact us on WhatsApp or try again later.",
        "tagline": "Peace of mind for your business.", "explore": "Explore", "contact": "Contact", "information": "Information", "legal": "Legal notice", "privacy": "Privacy", "client_login": "Client sign in", "rights": "All rights reserved.", "footer_note": "Built for businesses moving forward.",
        "close": "Close", "publisher": "Publisher:", "phone": "Phone:", "legal_text": "The information on this website is provided for general information. Full legal terms will be reviewed for the territories where Vericant operates.",
        "privacy_text_1": "Information submitted through the form is used only to respond to your request. To request access, correction or deletion of your information, contact vericant2023@gmail.com.", "privacy_text_2": "The public storefront uses a technical identifier to measure visits without showing your identity to merchants.",
        "whatsapp_demo_url": "https://wa.me/221708283254?text=Hello%20Vericant%2C%20I%20would%20like%20a%20demonstration.",
    },
}


def get_landing_copy(language: str) -> dict[str, str]:
    """Return complete landing copy, falling back to French for missing keys."""
    french = LANDING_COPY["fr"]
    if language == "fr":
        return french
    return {**french, **LANDING_COPY.get(language, {})}
