"""initial schema mysql indexed strings

Revision ID: d7a347885e2c
Revises: 
Create Date: 2026-04-03 05:46:00.372093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7a347885e2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('idx_category_shop', ['shop_id'], unique=False)
        batch_op.create_index('idx_category_shop_name', ['shop_id', 'name'], unique=True)
        batch_op.create_index('idx_category_type', ['type'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index('idx_client_phone', ['phone'], unique=False)
        batch_op.create_index('idx_client_shop', ['shop_id'], unique=False)
        batch_op.create_index('idx_client_shop_name', ['shop_id', 'name'], unique=False)

    op.create_table('shop_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shop_phones', schema=None) as batch_op:
        batch_op.create_index('idx_shop_phone_shop', ['shop_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index('idx_supplier_shop', ['shop_id'], unique=False)
        batch_op.create_index('idx_supplier_shop_name', ['shop_id', 'name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_shop_id', sa.Integer(), nullable=True),
    sa.Column('superadmin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['current_shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_active', ['is_active'], unique=False)
        batch_op.create_index('idx_user_current_shop', ['current_shop_id'], unique=False)
        batch_op.create_index('idx_user_name', ['name'], unique=True)

    op.create_table('boutique_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.REAL(), nullable=False),
    sa.Column('paid_amount', sa.REAL(), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boutique_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_boutique_transaction_category', ['category_id'], unique=False)
        batch_op.create_index('idx_boutique_transaction_date', ['date'], unique=False)
        batch_op.create_index('idx_boutique_transaction_shop', ['shop_id'], unique=False)

    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('payee_name', sa.String(length=255), nullable=False),
    sa.Column('withdrawal_amount', sa.REAL(), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'cashed', 'cancelled', 'bounced')"),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.create_index('idx_check_date', ['date'], unique=False)
        batch_op.create_index('idx_check_payee', ['shop_id', 'payee_name'], unique=False)
        batch_op.create_index('idx_check_shop', ['shop_id'], unique=False)
        batch_op.create_index('idx_check_status', ['status'], unique=False)

    op.create_table('employee_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('loan_amount', sa.REAL(), nullable=False),
    sa.Column('paid_amount', sa.REAL(), server_default='0', nullable=True),
    sa.Column('loan_date', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.Text(), nullable=True),
    sa.Column('loan_purpose', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=True),
    sa.Column('repayment_schedule', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("repayment_schedule IN ('monthly', 'weekly', 'one-time')"),
    sa.CheckConstraint("status IN ('active', 'paid', 'defaulted')"),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_loans', schema=None) as batch_op:
        batch_op.create_index('idx_employee_loan_date', ['loan_date'], unique=False)
        batch_op.create_index('idx_employee_loan_employee', ['employee_id'], unique=False)
        batch_op.create_index('idx_employee_loan_shop', ['shop_id'], unique=False)
        batch_op.create_index('idx_employee_loan_status', ['status'], unique=False)

    op.create_table('employee_salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('salary_amount', sa.REAL(), nullable=False),
    sa.Column('payment_date', sa.String(length=32), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('month_year', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='paid', nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("payment_method IN ('cash', 'bank', 'check')"),
    sa.CheckConstraint("status IN ('paid', 'pending', 'cancelled')"),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_salaries', schema=None) as batch_op:
        batch_op.create_index('idx_employee_salary_date', ['payment_date'], unique=False)
        batch_op.create_index('idx_employee_salary_employee', ['employee_id'], unique=False)
        batch_op.create_index('idx_employee_salary_month', ['month_year'], unique=False)
        batch_op.create_index('idx_employee_salary_shop', ['shop_id'], unique=False)
        batch_op.create_index('idx_employee_salary_status', ['status'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.REAL(), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('idx_expense_category', ['category_id'], unique=False)
        batch_op.create_index('idx_expense_date', ['date'], unique=False)
        batch_op.create_index('idx_expense_shop', ['shop_id'], unique=False)

    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('borrower_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.REAL(), nullable=False),
    sa.Column('paid_amount', sa.REAL(), server_default='0', nullable=True),
    sa.Column('loan_date', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'paid', 'defaulted')"),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index('idx_loan_borrower', ['shop_id', 'borrower_name'], unique=False)
        batch_op.create_index('idx_loan_date', ['loan_date'], unique=False)
        batch_op.create_index('idx_loan_shop', ['shop_id'], unique=False)
        batch_op.create_index('idx_loan_status', ['status'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index('idx_note_shop', ['shop_id'], unique=False)
        batch_op.create_index('idx_note_user', ['user_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('selling_price', sa.REAL(), nullable=False),
    sa.Column('buying_price', sa.REAL(), nullable=False),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('min_stock', sa.Integer(), server_default='0', nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('idx_product_category', ['category_id'], unique=False)
        batch_op.create_index('idx_product_shop', ['shop_id'], unique=False)
        batch_op.create_index('idx_product_shop_name', ['shop_id', 'name'], unique=False)
        batch_op.create_index('idx_product_stock', ['stock'], unique=False)

    op.create_table('sales_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.REAL(), nullable=False),
    sa.Column('paid_amount', sa.REAL(), server_default='0', nullable=False),
    sa.Column('remaining_amount', sa.REAL(), server_default='0', nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'paid', 'partially_paid', 'cancelled')"),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_bills', schema=None) as batch_op:
        batch_op.create_index('idx_sales_bill_client', ['client_id'], unique=False)
        batch_op.create_index('idx_sales_bill_date', ['date'], unique=False)
        batch_op.create_index('idx_sales_bill_number', ['shop_id', 'bill_number'], unique=True)
        batch_op.create_index('idx_sales_bill_shop', ['shop_id'], unique=False)
        batch_op.create_index('idx_sales_bill_status', ['status'], unique=False)
        batch_op.create_index('idx_sales_bill_user', ['user_id'], unique=False)

    op.create_table('supplier_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.Text(), nullable=False),
    sa.Column('amount', sa.REAL(), nullable=False),
    sa.Column('paid_amount', sa.REAL(), server_default='0', nullable=True),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_bills', schema=None) as batch_op:
        batch_op.create_index('idx_supplier_bill_date', ['date'], unique=False)
        batch_op.create_index('idx_supplier_bill_shop', ['shop_id'], unique=False)
        batch_op.create_index('idx_supplier_bill_supplier', ['supplier_id'], unique=False)

    op.create_table('user_shops',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'shop_id')
    )
    with op.batch_alter_table('user_shops', schema=None) as batch_op:
        batch_op.create_index('idx_user_shop_active', ['is_active'], unique=False)

    op.create_table('employee_loan_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.REAL(), nullable=False),
    sa.Column('payment_date', sa.String(length=32), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('processed_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("payment_method IN ('cash', 'bank', 'check')"),
    sa.ForeignKeyConstraint(['loan_id'], ['employee_loans.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_loan_payments', schema=None) as batch_op:
        batch_op.create_index('idx_employee_loan_payment_date', ['payment_date'], unique=False)
        batch_op.create_index('idx_employee_loan_payment_loan', ['loan_id'], unique=False)
        batch_op.create_index('idx_employee_loan_payment_method', ['payment_method'], unique=False)
        batch_op.create_index('idx_employee_loan_payment_shop', ['shop_id'], unique=False)

    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.REAL(), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("payment_method IN ('cash', 'card', 'check', 'transfer')"),
    sa.ForeignKeyConstraint(['bill_id'], ['sales_bills.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_payment_bill', ['bill_id'], unique=False)
        batch_op.create_index('idx_payment_date', ['date'], unique=False)
        batch_op.create_index('idx_payment_method', ['payment_method'], unique=False)
        batch_op.create_index('idx_payment_shop', ['shop_id'], unique=False)

    op.create_table('sales_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.REAL(), nullable=False),
    sa.Column('buying_price', sa.REAL(), nullable=False),
    sa.Column('total_amount', sa.REAL(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['sales_bills.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_details', schema=None) as batch_op:
        batch_op.create_index('idx_sales_detail_bill', ['bill_id'], unique=False)
        batch_op.create_index('idx_sales_detail_product', ['product_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("movement_type IN ('purchase', 'sale', 'adjustment', 'return')"),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index('idx_stock_movement_date', ['date'], unique=False)
        batch_op.create_index('idx_stock_movement_product', ['product_id'], unique=False)
        batch_op.create_index('idx_stock_movement_shop', ['shop_id'], unique=False)
        batch_op.create_index('idx_stock_movement_type', ['movement_type'], unique=False)

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_index('idx_shop_name', ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index('idx_shop_name')
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index('idx_stock_movement_type')
        batch_op.drop_index('idx_stock_movement_shop')
        batch_op.drop_index('idx_stock_movement_product')
        batch_op.drop_index('idx_stock_movement_date')

    op.drop_table('stock_movements')
    with op.batch_alter_table('sales_details', schema=None) as batch_op:
        batch_op.drop_index('idx_sales_detail_product')
        batch_op.drop_index('idx_sales_detail_bill')

    op.drop_table('sales_details')
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_payment_shop')
        batch_op.drop_index('idx_payment_method')
        batch_op.drop_index('idx_payment_date')
        batch_op.drop_index('idx_payment_bill')

    op.drop_table('payment_transactions')
    with op.batch_alter_table('employee_loan_payments', schema=None) as batch_op:
        batch_op.drop_index('idx_employee_loan_payment_shop')
        batch_op.drop_index('idx_employee_loan_payment_method')
        batch_op.drop_index('idx_employee_loan_payment_loan')
        batch_op.drop_index('idx_employee_loan_payment_date')

    op.drop_table('employee_loan_payments')
    with op.batch_alter_table('user_shops', schema=None) as batch_op:
        batch_op.drop_index('idx_user_shop_active')

    op.drop_table('user_shops')
    with op.batch_alter_table('supplier_bills', schema=None) as batch_op:
        batch_op.drop_index('idx_supplier_bill_supplier')
        batch_op.drop_index('idx_supplier_bill_shop')
        batch_op.drop_index('idx_supplier_bill_date')

    op.drop_table('supplier_bills')
    with op.batch_alter_table('sales_bills', schema=None) as batch_op:
        batch_op.drop_index('idx_sales_bill_user')
        batch_op.drop_index('idx_sales_bill_status')
        batch_op.drop_index('idx_sales_bill_shop')
        batch_op.drop_index('idx_sales_bill_number')
        batch_op.drop_index('idx_sales_bill_date')
        batch_op.drop_index('idx_sales_bill_client')

    op.drop_table('sales_bills')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('idx_product_stock')
        batch_op.drop_index('idx_product_shop_name')
        batch_op.drop_index('idx_product_shop')
        batch_op.drop_index('idx_product_category')

    op.drop_table('products')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index('idx_note_user')
        batch_op.drop_index('idx_note_shop')

    op.drop_table('notes')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index('idx_loan_status')
        batch_op.drop_index('idx_loan_shop')
        batch_op.drop_index('idx_loan_date')
        batch_op.drop_index('idx_loan_borrower')

    op.drop_table('loans')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('idx_expense_shop')
        batch_op.drop_index('idx_expense_date')
        batch_op.drop_index('idx_expense_category')

    op.drop_table('expenses')
    with op.batch_alter_table('employee_salaries', schema=None) as batch_op:
        batch_op.drop_index('idx_employee_salary_status')
        batch_op.drop_index('idx_employee_salary_shop')
        batch_op.drop_index('idx_employee_salary_month')
        batch_op.drop_index('idx_employee_salary_employee')
        batch_op.drop_index('idx_employee_salary_date')

    op.drop_table('employee_salaries')
    with op.batch_alter_table('employee_loans', schema=None) as batch_op:
        batch_op.drop_index('idx_employee_loan_status')
        batch_op.drop_index('idx_employee_loan_shop')
        batch_op.drop_index('idx_employee_loan_employee')
        batch_op.drop_index('idx_employee_loan_date')

    op.drop_table('employee_loans')
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_index('idx_check_status')
        batch_op.drop_index('idx_check_shop')
        batch_op.drop_index('idx_check_payee')
        batch_op.drop_index('idx_check_date')

    op.drop_table('checks')
    with op.batch_alter_table('boutique_transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_boutique_transaction_shop')
        batch_op.drop_index('idx_boutique_transaction_date')
        batch_op.drop_index('idx_boutique_transaction_category')

    op.drop_table('boutique_transactions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_user_name')
        batch_op.drop_index('idx_user_current_shop')
        batch_op.drop_index('idx_user_active')

    op.drop_table('users')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index('idx_supplier_shop_name')
        batch_op.drop_index('idx_supplier_shop')

    op.drop_table('suppliers')
    with op.batch_alter_table('shop_phones', schema=None) as batch_op:
        batch_op.drop_index('idx_shop_phone_shop')

    op.drop_table('shop_phones')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('idx_client_shop_name')
        batch_op.drop_index('idx_client_shop')
        batch_op.drop_index('idx_client_phone')

    op.drop_table('clients')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('idx_category_type')
        batch_op.drop_index('idx_category_shop_name')
        batch_op.drop_index('idx_category_shop')

    op.drop_table('categories')
    # ### end Alembic commands ###
